apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
  - name: url
    type: string
    description: The URL of the Git repository to clone.
    default: "https://github.com/yourusername/your-repo.git"
  workspaces:
  - name: workspace
  steps:
  - name: git-clone
    image: alpine/git
    script: |
      git clone -b main "$(params.url)" $(workspaces.workspace.path)/app
      mv $(workspaces.workspace.path)/app/* $(workspaces.workspace.path)/app/.* $(workspaces.workspace.path)
      ls