apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: zro-pipeline
spec:
  workspaces:
  - name: workspace
  tasks:
    - name: git-clone
      params:
       - name: url
         value: "https://github.com/babulalt/simple-go.git"
      workspaces:
      - name: workspace
        workspace: workspace
      taskRef:
        name: git-clone
    - name: list
      workspaces:
      - name: workspace
        workspace: workspace
      taskRef:
        name: list
      runAfter: 
        - git-clone
    - name: lint
      workspaces:
      - name: workspace
        workspace: workspace
      runAfter: 
        - git-clone
      taskRef:
        name: lint
    - name: test
      workspaces:
      - name: workspace
        workspace: workspace
      runAfter: 
        - lint
        - list
      taskRef:
        name: test
