apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: zro-pipeline-run
spec:
  pipelineRef:
    name: zro-pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
       spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
