apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
spec:
  workspaces:
  - name: workspace
  steps:
    - name: lint
      image: golangci/golangci-lint:v1.50.0
      script: |
        cd $(workspaces.workspace.path)
        ls
        echo "Lint task start..."
        golangci-lint run ./...
        echo "Lint completed"
        sleep 1