apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  workspaces:
  - name: workspace
  steps:
    - name: hello
      image: alpine
      script: |
        echo "hello world from path $(workspaces.workspace.path)"
        ls $(workspaces.workspace.path)
